/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://zky6mbhig5gljfup6aazdonkcu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-772izljczjgkxk4wpauho2s6ou",
    "aws_cognito_identity_pool_id": "us-east-2:04b694be-e42d-4dba-9f63-3e34c784e9b9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_8YZQpNwkI",
    "aws_user_pools_web_client_id": "6ja4v7sc0thj2v0tbni7kho2o3",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Login-fex63dj735cdtkg7gbwh4z466i-dev",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
